databases:
  - name: sexshop-db-final
    plan: free

services:
  # SexShop API
  - type: web
    name: sexshop-api
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: SexShop.API/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: UseSqlite
        value: "false"
      - key: UsePostgres
        value: "true"
      - key: ConnectionStrings__PostgresConnection
        fromDatabase:
          name: sexshop-db-final
          property: connectionString
      - key: JwtSettings__Key
        value: "Un_Secret_Muy_Largo_Y_Seguro_Para_SexShop_Pro_2024"
      - key: JwtSettings__Issuer
        value: "SexShopPro"
      - key: JwtSettings__Audience
        value: "SexShopPro"
      - key: JwtSettings__DurationInMinutes
        value: "1440"
