databases:
  - name: sexshop-db
    plan: free

services:
  # SexShop API
  - type: web
    name: sexshop-api
    plan: free
    runtime: docker
    dockerContext: .
    dockerfilePath: SexShop.API/Dockerfile
    envVars:
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: UseSqlite
        value: "false"
      - key: UsePostgres
        value: "true"
      - key: ConnectionStrings__PostgresConnection
        fromDatabase:
          name: sexshop-db
          property: connectionString
